site_name: Curso Xadrez Zacarias Campelo
site_description: Xadrez Básico
site_author: CER Daniel Robert
site_url: https://EmbaixadaZacariasCampelo.github.io/SiteZacariasCampelo/documentacao/

repo_name: EmbaixadaZacariasCampelo
repo_url: https://github.com/EmbaixadaZacariasCampelo/SiteZacariasCampelo

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  language: pt-BR
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Mudar para modo claro
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - def_list
  - attr_list

plugins:
  - search:
      lang:
        - pt-BR
        - en

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/embaixada.sibfragoso/
      name: Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/EmbaixadaZCsibemfragoso/?locale=pt_BR
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@EmbaixadaZacariaCampelo
      name: YouTube
    - icon: fontawesome/solid/envelope
      link: mailto:er.zacariascampelo@gmail.com
      name: Email
  generator: false

copyright: "Deus te abençoe"

nav:
  - Início: index.md

  - Módulo 1 (Xadrez Básico - Primeiros conceitos):
      - Aula 01 – Sobre o curso, Sobre o Jogo: Aula1.md
      - Aula 02 – Conceitos Básicos e Abertura: Aula2.md
      - Aula 03 – Meio Jogo, Treino de Tática: Aula3.md
      - Aula 04 – Treino de Mates: Aula4.md
      - Aula 05 – Análise de uma partida: Aula5.md

  - Materiais extras:
      - Glossário: Glossario.md

  - Teste Vídeo: TesteMK.md
