site_name: Curso Xadrez Zacarias Campelo
site_description: Xadrez Básico
site_author: CER Daniel Robert

site_url: https://EmbaixadaZacariasCampelo.github.io/SiteZacariasCampelo/documentacao/

theme:
  name: material

  language: pt-BR


nav:
  - Inicio: index.md

  - Módulo 1 (Xadrez Básico Primeiro conceitos):
      - Aula 01 – Sobre as aulas, Tabuleiro: Aula1.md
      - Aula 02 – Conceitos básicos, Peças e seus valores: Aula2.md
      - Aula 03 – Treino de Tática: Aula3.md
      - Aula 04 – Conceitos de abertura: Aula4.md
      - Aula 05 – Análise de uma partida: Aula5.md

    - Teste Video: TesteMK.md
